# frozen_string_literal: true

require: rubocop-rspec

inherit_from:
- https://relaxed.ruby.style/rubocop.yml

AllCops:
  DisplayStyleGuide: true
  DisplayCopNames: true
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'config/environments/*.rb'
    - 'bin/*'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'config/routes.rb'

Rails:
  Enabled: true

Rails/Output:
  Enabled: false

Style/DateTime:
  Enabled: true

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'Guardfile'
    - 'vendor/bundle'
    - 'coverage'

Style/ClassAndModuleChildren:
  Enabled: false
